export { default as ArtistInfo } from './pages/ArtistInfo/ArtistInfo.jsx'
export { default as ColouredHeartIcons } from './icons/ColourHeartIcons.jsx'
export { default as HeartIcons } from './icons/HeartIcons.jsx'
export { default as Home } from './Home/Home.jsx'
export { default as Navbar } from './Navbar/Navbar.jsx'
